Description: Correct paths used by program
Author: Nick Daly

Bug: <url in upstream bugtracker>
Forwarded: no
Reviewed-By: Petter Reinholdtsen <pere@hungry.com>
Last-Update: 2013-11-02

--- plinth-0.3.0.0.git.20131101.orig/cfg.py
+++ plinth-0.3.0.0.git.20131101/cfg.py
@@ -7,16 +7,16 @@ parser = SafeConfigParser(
         'root':os.path.dirname(os.path.realpath(__file__)),
         'product_name':"",
         'box_name':"",
-        'file_root':"",
-        'python_root':"",
-        'data_dir':"",
+        'file_root':"/usr/share/plinth/static",
+        'python_root':"/usr/share/plinth/python/plinth",
+        'data_dir':"/var/lib/plinth",
         'store_file':"",
         'user_db':"",
-        'status_log_file':"",
-        'access_log_file':"",
+        'status_log_file':"/var/log/plinth/status.log",
+        'access_log_file':"/var/log/plinth/access.log",
         'users_dir':"",
         'host':"127.0.0.1",
-        'pidfile':"",
+        'pidfile':"/var/run/plinth.pid",
         'port':"",
         })
 parser.read(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'plinth.config'))
